### ISSUE TITLE
Updates to readme.txt aren't committed unless version is bumped

### ISSUE THREAD

**Issue by nickcernis** [GaryJones/wordpress-plugin-git-flow-svn-deploy#14]
The deploy script doesn't seem to push readme changes in tagged folders unless you also bump the plugin version.

If your `$NEWVERSION1` hasn't changed since your last deploy, or if the same tagged folder already exists in SVN at WP.org, these two commands will place the `/trunk` directory inside the tagged local folder:

```
svn update --quiet $SVNPATH/tags/$NEWVERSION1
svn copy --quiet trunk/ tags/$NEWVERSION1/
```

The update command will pull the server copy of the tag from WP.org. The copy command will then copy the trunk folder into the tag folder, resulting in a local directory structure like this:

```
tags
  - 1.0.0
    - readme.txt [old version from WP.org]
    - trunk
      - readme.txt [new version from local trunk]
```

This line then deletes the new trunk subfolder:

`svn delete --force --quiet $SVNPATH/tags/$NEWVERSION1/trunk`

And no changes from the tagged directory are committed because the readme.txt in the tag folder is identical to the version on the server.

If I don't update the tag folder by removing the `update` command, a new tag folder is created by the `svn copy` command, and the contents of `trunk/` are placed inside of the tag folder:

```
#svn update --quiet $SVNPATH/tags/$NEWVERSION1
svn copy --quiet trunk/ tags/$NEWVERSION1/
```

Resulting in:

```
tags
  - 1.0.0
    - readme.txt [new version from local trunk]
```

The readme then gets updated when `svn commit` is called.

Is omitting the initial update a bad idea? (Presumably it will cause all files in the tag folder be committed as if they're new.) Perhaps there's a smarter way to handle this?

I know it's rare to make readme and screenshot tweaks without also bumping the plugin version, but the deploy script is so lovely to use that it would be great if it worked for copy tweaks and asset updates too.

**Comment by afragen** [comment]
Which branch are you referring to?

**Comment by nickcernis** [comment]
Develop – v1.0.0-dev2.

**Comment by afragen** [comment]
As a test, I just bumped my readme.txt to show Tested to 4.1.1 on https://wordpress.org/plugins/the-events-calendar-user-css/

Nothing else, not re-tagged. As you can see below and if you check the Compatible up to version number it now says 4.1.1

This using the develop branch.

```bash
..........................................

Preparing to deploy WordPress plugin

..........................................

readme.txt version: 1.4.0
the-events-calendar-user-css.php version: 1.4.0
Versions match in readme.txt and the-events-calendar-user-css.php. Let's proceed...
Changing to /Users/afragen/Documents/github/the-events-calendar-user-css/
Pushing git master to origin, with tags
Everything up-to-date
Everything up-to-date

Creating local copy of SVN repo trunk ...
A    /tmp/the-events-calendar-user-css/tags
A    /tmp/the-events-calendar-user-css/assets
A    /tmp/the-events-calendar-user-css/trunk
A    /tmp/the-events-calendar-user-css/branches
Checked out revision 1114873.
Ignoring GitHub specific files
property 'svn:ignore' set on '/tmp/the-events-calendar-user-css/trunk'
Exporting the HEAD of master from git to the trunk of SVN
Moving assets
mv: rename /tmp/the-events-calendar-user-css/trunk/assets/* to /tmp/the-events-calendar-user-css/assets/*: No such file or directory
svn: E125001: '/tmp/the-events-calendar-user-css/trunk/assets' does not exist
Changing directory to SVN and committing to trunk
Sending        readme.txt
Transmitting file data .
Committed revision 1114874.
Updating WordPress plugin repo assets and committing
Updating '/tmp/the-events-calendar-user-css/assets/*':
At revision 1114874.
Creating new SVN tag and committing it
svn: E125001: '/tmp/the-events-calendar-user-css/tags/1.4.0/assets' does not exist
Removing temporary directory /tmp/the-events-calendar-user-css
*** FIN ***
```

Are you seeing something different?

**Comment by nickcernis** [comment]
Thanks for testing this. Here's what I see:

```sh
Preparing to deploy WordPress plugin

..........................................

readme.txt version: 0.1.2
gnu-terry-pratchett.php version: 0.1.2
Versions match in readme.txt and gnu-terry-pratchett.php. Let's proceed...
Changing to /Users/nick/Dropbox/Play/WordPress/plugins.dev/wp-content/plugins/gnu-terry-pratchett/
Pushing git master to origin, with tags
Everything up-to-date
Everything up-to-date

Creating local copy of SVN repo trunk ...
A    /tmp/gnu-terry-pratchett/tags
A    /tmp/gnu-terry-pratchett/assets
A    /tmp/gnu-terry-pratchett/trunk
A    /tmp/gnu-terry-pratchett/branches
Checked out revision 1114878.
Ignoring GitHub specific files
property 'svn:ignore' set on '/tmp/gnu-terry-pratchett/trunk'
Exporting the HEAD of master from git to the trunk of SVN
Moving assets
mv: rename /tmp/gnu-terry-pratchett/trunk/assets/* to /tmp/gnu-terry-pratchett/assets/*: No such file or directory
svn: E125001: '/tmp/gnu-terry-pratchett/trunk/assets' does not exist
Changing directory to SVN and committing to trunk
Sending        readme.txt
Transmitting file data .
Committed revision 1114879.
Updating WordPress plugin repo assets and committing
Updating '/tmp/gnu-terry-pratchett/assets/*':
At revision 1114879.
Creating new SVN tag and committing it
svn: E125001: '/tmp/gnu-terry-pratchett/tags/0.1.2/assets' does not exist
Removing temporary directory /tmp/gnu-terry-pratchett
*** FIN ***
```

My output is the same as yours, but my readme in the tagged folder isn't updated.

The [trunk readme.txt](http://plugins.svn.wordpress.org/gnu-terry-pratchett/trunk/readme.txt) contains the new text _“The GNU Terry Pratchett plugin transmits an "X-Clacks-Overhead" header”._

The [0.1.2 tag readme.txt](http://plugins.svn.wordpress.org/gnu-terry-pratchett/tags/0.1.2/readme.txt) has the old text: _The GNU Terry Pratchett plugin transmits a special "X-Clacks-Overhead" header_ (The word “special” is still present.)

It looks like your readme has the same issue, though: I see 4.1.1 in the [trunk readme](http://plugins.svn.wordpress.org/the-events-calendar-user-css/trunk/readme.txt) and 4.1 in the [1.4.0 readme](http://plugins.svn.wordpress.org/the-events-calendar-user-css/tags/1.4.0/readme.txt).

My [plugin page](https://wordpress.org/plugins/gnu-terry-pratchett/) is using the 0.1.2 readme as opposed to the one in trunk. Not sure why your plugin page is showing 4.1.1 as the latest version when you have the stable tag set to 1.4.0, though, unless perhaps WP uses the trunk readme for that?

**Comment by afragen** [comment]
Isn't the point of updating the readme.txt or plugin page images so that the current info is on the plugin page? The plugin repo takes it's info for display from trunk. 

Yes the plugin repo only downloads or updates from the tagged branch but how many users actually look at the installed plugin for readme info?

**Comment by afragen** [comment]
![screenshot_06](https://cloud.githubusercontent.com/assets/1296790/6699222/0da1ca70-ccbd-11e4-8723-4c6901630e3e.png)

Looks like the new version is being displayed, though it won't be in the download.

**Comment by nickcernis** [comment]
The latest version (trunk) doesn't have the word 'special' in it, so that should not be appearing in the description there.

WP.org is pulling the description from the version [0.1.2 tag folder](http://plugins.svn.wordpress.org/gnu-terry-pratchett/tags/0.1.2/). The deploy script updated the readme in trunk, but not the one in 0.1.2, even though that's marked as the stable tag.

> The plugin repo takes it's info for display from trunk.

It doesn't appear to. It seems to take the description from the stable tag folder readme. Here's my [trunk readme.txt](http://plugins.svn.wordpress.org/gnu-terry-pratchett/trunk/readme.txt) (top) next to the WP page (bottom):

![plugins_svn_wordpress_org_gnu-terry-pratchett_trunk_readme_txt_and_wordpress_ _gnu_terry_pratchett_ _wordpress_plugins](https://cloud.githubusercontent.com/assets/647669/6699369/52d1ef44-ccf9-11e4-91f1-8e743da98b0c.jpg)

**Comment by nickcernis** [comment]
[This explanation from Otto](https://make.wordpress.org/plugins/2012/06/09/the-plugins-directory-and-readme-txt-files/) helps a little:

> If the Stable Tag is set to anything else, then it will go and look in /tags/ for the referenced version. So a Stable Tag of “1.2.3” will make it look for /tags/1.2.3/.

> **Important bit:** Everything else is read from this new location. If the Stable Tag is 1.2.3 and /tags/1.2.3/ exists, then nothing in trunk will be read any further for parsing by any part of the system. If you try to change the description of the plugin in /trunk/readme.txt, and Stable Tag isn’t trunk, then your changes won’t do anything on your plugin page. Everything comes from the readme.txt in the file being pointed to by the Stable Tag.

It sounds like WP scans the readme in trunk, gets all the info up until the stable tag, and then goes off to that stable tag folder for the description and everything else.

**Comment by afragen** [comment]
I'm confused. You changed the first line of the description to include "special" or to remove it? I just updated the Compatible with header.

Alternately, you could list `Stable tag: trunk`

**Comment by nickcernis** [comment]
I changed the first line to remove “special”. Trunk has that change and displays the sentence without “special”. The stable tag folder and the WP listing still contains “special”, which is part of the old description. (Sorry for any confusion!)

I thought about setting the stable tab and removing the deploy script's version check, but I wanted to report the issue in case it affects anyone else. (It's handy to be able to define a stable tag that isn't trunk sometimes too.)

It looks like the [master branch](https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy/blob/master/deploy.sh#L106) doesn't run `svn update` before the `copy`:

Master:

```sh
echo "Creating new SVN tag and committing it"
cd $SVNPATH
svn copy trunk/ tags/$NEWVERSION1/
cd $SVNPATH/tags/$NEWVERSION1
svn commit --username=$SVNUSER -m "Tagging version $NEWVERSION1"
```

Dev:
```sh
echo "Creating new SVN tag and committing it"
cd $SVNPATH
svn update --quiet $SVNPATH/tags/$NEWVERSION1
svn copy --quiet trunk/ tags/$NEWVERSION1/
# Remove assets and trunk directories from tag directory
svn delete --force --quiet $SVNPATH/tags/$NEWVERSION1/assets
svn delete --force --quiet $SVNPATH/tags/$NEWVERSION1/trunk
cd $SVNPATH/tags/$NEWVERSION1
svn commit --username=$SVNUSER -m "Tagging version $NEWVERSION1"
```

Is dropping the `update` likely to cause any harm?

**Comment by afragen** [comment]
`master` is quite a bit behind `develop`. You can always comment out the line and see what happens.

The fact is that this peculiarity is really part of wp.org and not the script. If you've made a change to your local git repo without pushing a tag then only trunk will be updated. By definition a tag is a snapshot in time and shouldn't really be changed.

Try the above change to `Stable tag: trunk` and see if whole of the new readme isn't displayed in wp.org.

**Comment by nickcernis** [comment]
I removed the version check, set `Stable tag: trunk` in the readme, and changed `NEWVERSION1` to use the plugin version:

```sh
NEWVERSION1=`grep "Version:" $GITPATH/$MAINFILE | awk -F' ' '{print $NF}' | tr -d '\r'`
echo "$MAINFILE version: $NEWVERSION1"
```

WordPress now uses the trunk folder for the entire readme, so all readme updates are pushed successfully without bumping the version. It seems like a healthy compromise.

Thanks for working through this with me – I really appreciate it. You're welcome to close the issue if you don't plan to make any related changes.

**Comment by afragen** [comment]
@nickcernis you are very welcome. I'll leave the issue open in case @GaryJones wants to chime in.

> and changed NEWVERSION1 to use the plugin version:
> 
>    NEWVERSION1=`grep "Version:" $GITPATH/$MAINFILE | awk -F' ' '{print $NF}' | tr -d '\r'`
>    echo "$MAINFILE version: $NEWVERSION1"

I don't know whether or not this change effects the check to ensure both readme.txt and plugin have same version number.

**Comment by nickcernis** [comment]
I removed that version check. Otherwise the script tries to compare 0.1.2 with 'trunk', sees that they mismatch, and won't continue. 

Perhaps I should have added a check to see if the stable tag is trunk, then skip the version check in those cases. That would keep the version check in place for any other plugins I develop that use a version number as the stable tag.

**Comment by afragen** [comment]
Maybe I'll try to add a check if Stable tag is trunk to continue.

**Comment by afragen** [comment]
Download the latest `develop` branch. https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy/commit/7ad1de56acc99ffde7d0b840e92a20c1ab4cb96a

**Comment by nickcernis** [comment]
If the stable tag is trunk, I think you also need to set `NEWVERSION1` to the plugin version stored in `NEWVERSION2`.

Otherwise, `NEWVERSION1` will contain 'trunk', and the new tagged folder for your release will be at `/tags/trunk/` instead of `/tags/[your-new-version]/`.

```sh
if [ "$NEWVERSION1" = "trunk" ]; then
	# Use the version number from the plugin file
	NEWVERSION1 = ${NEWVERSION2}
	echo "Version in readme.txt & $MAINFILE don't match, but Stable tag is trunk. Let's proceed..."
elif [ "$NEWVERSION1" != "$NEWVERSION2" ]; then
	echo "Version in readme.txt & $MAINFILE don't match. Exiting...."
	exit 1;
elif [ "$NEWVERSION1" = "$NEWVERSION2" ]; then
	echo "Versions match in readme.txt and $MAINFILE. Let's proceed..."
fi
```

I tested that and it works for a readme update. I've not tried deploying a new version yet.

**Comment by nickcernis** [comment]
Actually, it might make things more maintainable to just switch `NEWVERSION1` to be the plugin version and `NEWVERSION2` to be the readme version.

That avoids the potentially confusing 'version1 = version2' stuff.

Naming the variables `PLUGINVERSION` and `READMEVERSION` and then using PLUGINVERSION when referring to the version number later on could also help with legibility. e.g.

```sh

# Check version in readme.txt is the same as plugin file after translating both to unix line breaks to work around grep's failure to identify mac line breaks
PLUGINVERSION=`grep "Version:" $GITPATH/$MAINFILE | awk -F' ' '{print $NF}' | tr -d '\r'`
echo "$MAINFILE version: $PLUGINVERSION"
READMEVERSION=`grep "^Stable tag:" $GITPATH/readme.txt | awk -F' ' '{print $NF}' | tr -d '\r'`
echo "readme.txt version: $READMEVERSION"

if [ "$READMEVERSION" = "trunk" ]; then
	echo "Version in readme.txt & $MAINFILE don't match, but Stable tag is trunk. Let's proceed..."
elif [ "$PLUGINVERSION" != "$READMEVERSION" ]; then
	echo "Version in readme.txt & $MAINFILE don't match. Exiting...."
	exit 1;
elif [ "$PLUGINVERSION" = "$READMEVERSION" ]; then
	echo "Versions match in readme.txt and $MAINFILE. Let's proceed..."
fi
```

And then later:

```sh
echo "Creating new SVN tag and committing it"
cd $SVNPATH
svn update --quiet $SVNPATH/tags/$PLUGINVERSION
svn copy --quiet trunk/ tags/$PLUGINVERSION/
# Remove assets and trunk directories from tag directory
svn delete --force --quiet $SVNPATH/tags/$PLUGINVERSION/assets
svn delete --force --quiet $SVNPATH/tags/$PLUGINVERSION/trunk
cd $SVNPATH/tags/$PLUGINVERSION
svn commit --username=$SVNUSER -m "Tagging version $PLUGINVERSION"
```
