### ISSUE TITLE
'/tmp/my-plugin/tags/2.3.0/assets' does not exist

### ISSUE THREAD

**Issue by flowdee** [GaryJones/wordpress-plugin-git-flow-svn-deploy#21]
Using the scripts works fine every time I used it but today I received the following issue:

```
Summary of updates:
  Updated '/tmp/my-plugin/assets/banner-1544x500.jpg' to r1407642.
  Updated '/tmp/my-plugin/assets/banner-772x250.jpg' to r1407642.
  Updated '/tmp/my-plugin/assets/icon-128x128.png' to r1407642.
  Updated '/tmp/my-plugin/assets/icon-256x256.png' to r1407642.
  Updated '/tmp/my-plugin/assets/screenshot-1.png' to r1407642.
  Updated '/tmp/my-plugin/assets/screenshot-2.png' to r1407642.
Creating new SVN tag and committing it
svn: E125001: '/tmp/my-plugin/tags/2.3.0/assets' does not exist
Removing temporary directory /tmp/my-plugin
*** FIN ***
```

All files are pushed to git and WP repo, except the git tag was not published and the WP.org plugin version was not updated. When downloading the plugin it already includes the new release.

Any idea? Really strange. I'm not a SVN friend that's why I use this script :)

**Comment by afragen** [comment]
Which branch of this script are you using? `develop` is further along.

**Comment by flowdee** [comment]
develop branch

**Comment by afragen** [comment]
Did you create a tag locally?

**Comment by flowdee** [comment]
nope. just as everytime made my changes, committed and executed the script

**Comment by flowdee** [comment]
I manually cleaned up some files in the svn and then committed it manually. Hope this was an unique issue.
