### ISSUE TITLE
Add software license

### ISSUE THREAD

**Issue by jhabdas** [GaryJones/wordpress-plugin-git-flow-svn-deploy#30]
This script looks interesting as it solves a common problem I believe may be holding back many plug-in developers from contributing WordPress plugins to [wp.org](https://wp.org). Thanks for putting it together. Any plans on adding a software license for your portion or the copied code portions?

Looking over the list it looks like a lot of the code is under L/GPL or is trying to be, [one item](https://github.com/BFTrick/jotform-integration) is without license and the other linked resource from the GH/Jekyll god is has a link which rotted, making it difficult to determine if it's okay to copy parts of this software.

Thanks for your help.

**Comment by GaryJones** [comment]
Thanks for raising this.

I can see that Dean's license only got [created](https://github.com/deanc/wordpress-plugin-git-svn/commit/d4ac2c205e54c3851a34fa1c4dc39bc1c0f2f039) a month ago, and that Brent's was [added](https://github.com/thenbrent/multisite-user-management/commit/eee4f4378d7b37865a738caa48d475edaa2a07e2) a few months back.

This project was forked before their licenses existed - which may well be a problem in itself.

I'm happy for this project to be L/GPL (I need to look more at what the difference is), or to be MIT.

Either way, for my amendments at least, go ahead and copy, modify and do what you need for your circumstances.

**Comment by jhabdas** [comment]
Sounds good, @GaryJones. Thanks so much. Very happy to have this repo as I saw several of the others during the search. Nice to see others putting licenses in place to help open up the code. I'll close this for now give it's on your radar. Please feel free to reopen if desired.

**Comment by jhabdas** [comment]
FYI https://github.com/BFTrick/jotform-integration/issues/6#issuecomment-328109465

**Comment by GaryJones** [comment]
I've clarified the best I can what the license situation is.
